services:
  app:
    image: munix244/lol_analysis_app:latest
    build: .
    container_name: lol_analysis_app
    restart: unless-stopped
    environment:
      - dbserverandport=
      - dbdatabase=
      - dbusr=
      - dbpwd=
      - riotapikey=RGAPI-08cc3e12-9798-49f9-933c-b3c4178adf73
    volumes:
      - ./:/app
    # If you need to attach to the running container for debugging:
    # stdin_open: true
    # tty: true
